services:
    nginx:
        image: nginx:1.23.0
        volumes:
            - type: volume
              source: nginx_data
              target: /var/www/html
            - type: bind
              source: ./nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
            - type: bind
              source: ./nginx/kobizo-task-management.conf
              target: /etc/nginx/conf.d/kobizo-task-management.conf
            - type: bind
              source: ../fe
              target: /var/www/html/source
        ports:
            - '81:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        deploy:
            resources:
                limits:
                    memory: 2G
                reservations:
                    memory: 512M
    php:
        build: ./php
        volumes:
            - type: volume
              source: php_data
              target: /var/www/html
            - type: bind
              source: ./php/fpm/memory.ini
              target: /usr/local/etc/php/conf.d/docker-php-memlimit.ini
            - type: bind
              source: ./php/xdebug/xdebug.ini
              target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - type: bind
              source: ../fe
              target: /var/www/html/source
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 512M
    redis6379:
      image: redis:7.0.2
      restart: always
      deploy:
        resources:
          limits:
            memory: 2G
          reservations:
            memory: 512M
networks:
    internal:
        ipam:
            driver: default

volumes:
    nginx_data:
    php_data:
